apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    helm.sh/chart: {{ include "flaskapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
