apiVersion: batch/v1
kind: CronJob
metadata:
  name: call-flask-app
spec:
  schedule: "*/1 * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            args:
            - /bin/sh
            - -c
            - curl http://flask-service:5000
          restartPolicy: OnFailure

