apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-health-check
spec:
  containers:
    - name: flask-container
      image: erezazu/devops0405-docker-flask-app:v1
      ports:
        - containerPort: 5000
      readinessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 3
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 5

