# flask-pod-with-secret-volume.yaml
# This file defines a Pod that mounts a Secret as a Volume
# The secret files will be available inside the container at /etc/secrets

apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-secret
spec:
  containers:
  - name: flask-container
    image: erezazu/devops0405-docker-flask-app:v1
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: flask-secret

