apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
spec:
  containers:
  - name: flask-container
    image: erezazu/devops0405-docker-flask-app:v1
    ports:
    - containerPort: 5000
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: flask-configmap
          key: APP_ENV
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: flask-configmap
          key: LOG_LEVEL
    - name: FLASK_PORT
      valueFrom:
        configMapKeyRef:
          name: flask-configmap
          key: FLASK_PORT

