apiVersion: v2
name: flaskapp
description: Helm chart for the Flaskapp (Phase 3)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.13

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0.1.13

#Test First Trigger
# trigger
# trigger Mon Aug 11 21:17:02 JDT 2025
# trigger Mon Aug 11 21:22:56 JDT 2025
# trigger Mon Aug 11 21:29:16 JDT 2025
# trigger Mon Aug 11 21:53:28 JDT 2025
# trigger Mon Aug 11 22:05:22 JDT 2025
# trigger Mon Aug 11 22:23:55 JDT 2025
# trigger Mon Aug 11 22:31:09 JDT 2025
# trigger Tue Aug 12 12:12:29 JDT 2025
# trigger Tue Aug 12 13:01:35 JDT 2025
# trigger Tue Aug 12 13:15:00 JDT 2025
# trigger Tue Aug 12 13:23:21 JDT 2025
# trigger Tue Aug 12 16:23:00 JDT 2025
# trigger Thu Aug 14 10:15:22 JDT 2025
# trigger Thu Aug 14 12:30:07 JDT 2025
# trigger Thu Aug 14 12:33:21 JDT 2025
# trigger Thu Aug 14 12:34:50 JDT 2025
