image:
  repository: docker.io/erezazu/devops0405-docker-flask-app
  tag: "latest"   # default; Jenkins overrides with SHA tag at deploy time
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 5000

service:
  type: ClusterIP
  port: 80
# trigger Thu Aug 14 23:50:40 JDT 2025
# trigger Thu Aug 14 23:55:06 JDT 2025
# trigger Fri Aug 15 00:02:26 JDT 2025
