image:
  repository: docker.io/erezazu/devops0405-docker-flask-app
  tag: "latest"        
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 5000

service:
  type: NodePort
  port: 5000
  nodePort: 30500
