image:
  repository: docker.io/erezazu/devops0405-docker-flask-app
  tag: "latest"   # default; Jenkins overrides with SHA tag at deploy time
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 5000

service:
  type: ClusterIP
  port: 80
